services:
  postgres:
    image: postgres:16-alpine
    container_name: huyetmach175_db_container
    restart: always
    environment:
      POSTGRES_DB: huyetmach175_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    networks:
      - huyetmach175_net

volumes:
  pgdata:

networks:
  huyetmach175_net:
    driver: bridge
