// <auto-generated />
using System;
using HuyetMach175.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HuyetMach175.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261008090126_AddStaffCodeToUserTable")]
    partial class AddStaffCodeToUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.AuditLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_type");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("change_reason");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewState")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("new_state");

                    b.Property<string>("OldState")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_state");

                    b.Property<int?>("PerformedBy")
                        .HasColumnType("integer")
                        .HasColumnName("performed_by");

                    b.Property<int>("RecordId")
                        .HasColumnType("integer")
                        .HasColumnName("record_id");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("table_name");

                    b.HasKey("LogId");

                    b.HasIndex("PerformedBy");

                    b.HasIndex("TableName", "RecordId", "CreatedAt")
                        .HasDatabaseName("idx_audit_logs_record");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.BloodAllocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("allocation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AllocationId"));

                    b.Property<int>("BagId")
                        .HasColumnType("integer")
                        .HasColumnName("bag_id");

                    b.Property<DateTime?>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<int?>("IssuedBy")
                        .HasColumnType("integer")
                        .HasColumnName("issued_by");

                    b.Property<int?>("ReceivedBy")
                        .HasColumnType("integer")
                        .HasColumnName("received_by");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reserved_at");

                    b.Property<int>("ReservedBy")
                        .HasColumnType("integer")
                        .HasColumnName("reserved_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("AllocationId");

                    b.HasIndex("BagId")
                        .IsUnique()
                        .HasDatabaseName("uq_active_allocation_per_bag")
                        .HasFilter("status IN ('RESERVED', 'ISSUED')");

                    b.HasIndex("IssuedBy");

                    b.HasIndex("ReceivedBy");

                    b.HasIndex("RequestId");

                    b.HasIndex("ReservedBy");

                    b.ToTable("blood_allocations");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.BloodBag", b =>
                {
                    b.Property<int>("BagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bag_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BagId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barcode");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("blood_type");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("component_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DiscardReason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("discard_reason");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<int?>("ParentBagId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_bag_id");

                    b.Property<string>("RhFactor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rh_factor");

                    b.Property<int?>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("VolumeMl")
                        .HasColumnType("integer")
                        .HasColumnName("volume_ml");

                    b.HasKey("BagId");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("ComponentTypeId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ParentBagId");

                    b.HasIndex("SessionId");

                    b.HasIndex("BloodType", "RhFactor", "ComponentTypeId", "Status", "ExpiredAt")
                        .HasDatabaseName("idx_blood_bags_lookup");

                    b.ToTable("blood_bags");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.BloodComponentType", b =>
                {
                    b.Property<int>("ComponentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("component_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ComponentTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<int>("LifeDays")
                        .HasColumnType("integer")
                        .HasColumnName("life_days");

                    b.Property<string>("StorageTemperature")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("storage_temperature");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_code");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type_name");

                    b.HasKey("ComponentTypeId");

                    b.HasIndex("TypeCode")
                        .IsUnique();

                    b.ToTable("blood_component_types");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.BloodRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("diagnosis");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("integer")
                        .HasColumnName("doctor_id");

                    b.Property<string>("PatientBloodType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("patient_blood_type");

                    b.Property<string>("PatientCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("patient_code");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("patient_name");

                    b.Property<string>("PatientRh")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("patient_rh");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("RequestCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("request_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("UrgencyLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("urgency_level");

                    b.HasKey("RequestId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("RequestCode")
                        .IsUnique();

                    b.ToTable("blood_requests");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.BloodRequestItem", b =>
                {
                    b.Property<int>("RequestItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("request_item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestItemId"));

                    b.Property<int>("AllocatedUnits")
                        .HasColumnType("integer")
                        .HasColumnName("allocated_units");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("component_type_id");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    b.Property<int>("RequestedUnits")
                        .HasColumnType("integer")
                        .HasColumnName("requested_units");

                    b.HasKey("RequestItemId");

                    b.HasIndex("ComponentTypeId");

                    b.HasIndex("RequestId");

                    b.ToTable("blood_request_items");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.BloodReturn", b =>
                {
                    b.Property<int>("ReturnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("return_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReturnId"));

                    b.Property<int>("AllocationId")
                        .HasColumnType("integer")
                        .HasColumnName("allocation_id");

                    b.Property<string>("FinalAction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("final_action");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<bool>("Qualified")
                        .HasColumnType("boolean")
                        .HasColumnName("qualified");

                    b.Property<int>("ReceivedBy")
                        .HasColumnType("integer")
                        .HasColumnName("received_by");

                    b.Property<string>("ReturnReason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("return_reason");

                    b.Property<int>("ReturnedBy")
                        .HasColumnType("integer")
                        .HasColumnName("returned_by");

                    b.HasKey("ReturnId");

                    b.HasIndex("AllocationId")
                        .IsUnique();

                    b.HasIndex("ReceivedBy");

                    b.HasIndex("ReturnedBy");

                    b.ToTable("blood_returns");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.BloodTestResult", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("test_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TestId"));

                    b.Property<int>("BagId")
                        .HasColumnType("integer")
                        .HasColumnName("bag_id");

                    b.Property<string>("ConfirmedBloodType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("confirmed_blood_type");

                    b.Property<string>("ConfirmedRh")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("confirmed_rh");

                    b.Property<string>("HbvResult")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hbv_result");

                    b.Property<string>("HcvResult")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hcv_result");

                    b.Property<string>("HivResult")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hiv_result");

                    b.Property<string>("IrregularAntibody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("irregular_antibody");

                    b.Property<string>("OverallConclusion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("overall_conclusion");

                    b.Property<string>("SyphilisResult")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("syphilis_result");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("integer")
                        .HasColumnName("technician_id");

                    b.Property<DateTime>("TestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tested_at");

                    b.HasKey("TestId");

                    b.HasIndex("BagId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("blood_test_results");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("department_code");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department_name");

                    b.HasKey("DepartmentId");

                    b.HasIndex("DepartmentCode")
                        .IsUnique();

                    b.ToTable("departments");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.DonationAppointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("appointment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date")
                        .HasColumnName("appointment_date");

                    b.Property<int?>("CampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime?>("CheckedInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_in_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DonorId")
                        .HasColumnType("integer")
                        .HasColumnName("donor_id");

                    b.Property<bool>("IsWalkIn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_walk_in");

                    b.Property<string>("QrCodeToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("qr_code_token");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("time_slot");

                    b.HasKey("AppointmentId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("QrCodeToken")
                        .IsUnique();

                    b.HasIndex("DonorId", "AppointmentDate")
                        .IsUnique()
                        .HasDatabaseName("uq_active_appointment_per_day")
                        .HasFilter("status = 'BOOKED'");

                    b.ToTable("donation_appointments");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.DonationCampaign", b =>
                {
                    b.Property<int>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("campaign_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CampaignId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer")
                        .HasColumnName("approved_by");

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("campaign_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location_name");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TargetDonations")
                        .HasColumnType("integer")
                        .HasColumnName("target_donations");

                    b.HasKey("CampaignId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CreatedBy");

                    b.ToTable("donation_campaigns");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.DonationSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SessionId"));

                    b.Property<int?>("ActualVolumeMl")
                        .HasColumnType("integer")
                        .HasColumnName("actual_volume_ml");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer")
                        .HasColumnName("appointment_id");

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("blood_pressure");

                    b.Property<string>("CollectionIncident")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("collection_incident");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("DeferralReason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("deferral_reason");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer")
                        .HasColumnName("doctor_id");

                    b.Property<decimal?>("HemoglobinLevel")
                        .HasColumnType("numeric")
                        .HasColumnName("hemoglobin_level");

                    b.Property<int?>("PhlebotomistId")
                        .HasColumnType("integer")
                        .HasColumnName("phlebotomist_id");

                    b.Property<string>("ScreeningStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("screening_status");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TargetVolumeMl")
                        .HasColumnType("text")
                        .HasColumnName("target_volume_ml");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("weight_kg");

                    b.HasKey("SessionId");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("DoctorId");

                    b.HasIndex("PhlebotomistId");

                    b.ToTable("donation_sessions");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.Donor", b =>
                {
                    b.Property<int>("DonorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("donor_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DonorId"));

                    b.Property<string>("BloodType")
                        .HasColumnType("text")
                        .HasColumnName("blood_type");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("citizen_id");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender");

                    b.Property<DateOnly?>("LastDonationDate")
                        .HasColumnType("date")
                        .HasColumnName("last_donation_date");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RhFactor")
                        .HasColumnType("text")
                        .HasColumnName("rh_factor");

                    b.Property<int>("TotalDonations")
                        .HasColumnType("integer")
                        .HasColumnName("total_donations");

                    b.HasKey("DonorId");

                    b.HasIndex("CitizenId")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("donors");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("notification_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<int?>("RecipientUserId")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_user_id");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("integer")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("text")
                        .HasColumnName("reference_type");

                    b.Property<int?>("TargetDepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("target_department_id");

                    b.Property<int?>("TargetRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("target_role_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("NotificationId");

                    b.HasIndex("TargetDepartmentId");

                    b.HasIndex("TargetRoleId")
                        .HasDatabaseName("idx_notifications_target_role")
                        .HasFilter("target_role_id IS NOT NULL");

                    b.HasIndex("RecipientUserId", "IsRead")
                        .HasDatabaseName("idx_notifications_recipient_unread")
                        .HasFilter("is_read = FALSE");

                    b.ToTable("notification");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("permission_code");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission_name");

                    b.HasKey("PermissionId");

                    b.HasIndex("PermissionCode")
                        .IsUnique();

                    b.ToTable("permissions");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.PreScreeningSurvey", b =>
                {
                    b.Property<int>("SurveyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("survey_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SurveyId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer")
                        .HasColumnName("appointment_id");

                    b.Property<bool>("HasRisk")
                        .HasColumnType("boolean")
                        .HasColumnName("has_risk");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("risk_score");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("SurveyAnswers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("survey_answers");

                    b.HasKey("SurveyId");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("pre_screening_surveys");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.RefreshToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("token_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_code");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleCode")
                        .IsUnique();

                    b.ToTable("roles");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.StorageLocation", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocationId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFull")
                        .HasColumnType("boolean")
                        .HasColumnName("is_full");

                    b.Property<string>("RefrigeratorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("refrigerator_name");

                    b.Property<string>("ShelfNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("shelf_number");

                    b.Property<decimal>("TargetTemperature")
                        .HasColumnType("numeric")
                        .HasColumnName("target_temperature");

                    b.HasKey("LocationId");

                    b.ToTable("storage_locations");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone_number");

                    b.Property<string>("StaffCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("staff_code");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("StaffCode")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.AuditLog", b =>
                {
                    b.HasOne("HuyetMach175.Api.Data.Entities.User", "PerformedByUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("PerformedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.BloodAllocation", b =>
                {
                    b.HasOne("HuyetMach175.Api.Data.Entities.BloodBag", "Bag")
                        .WithMany("Allocations")
                        .HasForeignKey("BagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HuyetMach175.Api.Data.Entities.User", "IssuedByUser")
                        .WithMany("IssuedAllocations")
                        .HasForeignKey("IssuedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HuyetMach175.Api.Data.Entities.User", "ReceivedByUser")
                        .WithMany("ReceivedAllocations")
                        .HasForeignKey("ReceivedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HuyetMach175.Api.Data.Entities.BloodRequest", "Request")
                        .WithMany("Allocations")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HuyetMach175.Api.Data.Entities.User", "ReservedByUser")
                        .WithMany("ReservedAllocations")
                        .HasForeignKey("ReservedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bag");

                    b.Navigation("IssuedByUser");

                    b.Navigation("ReceivedByUser");

                    b.Navigation("Request");

                    b.Navigation("ReservedByUser");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.BloodBag", b =>
                {
                    b.HasOne("HuyetMach175.Api.Data.Entities.BloodComponentType", "ComponentType")
                        .WithMany("BloodBags")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HuyetMach175.Api.Data.Entities.StorageLocation", "Location")
                        .WithMany("BloodBags")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HuyetMach175.Api.Data.Entities.BloodBag", "ParentBag")
                        .WithMany("DerivedBags")
                        .HasForeignKey("ParentBagId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HuyetMach175.Api.Data.Entities.DonationSession", "Session")
                        .WithMany("BloodBags")
                        .HasForeignKey("SessionId");

                    b.Navigation("ComponentType");

                    b.Navigation("Location");

                    b.Navigation("ParentBag");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.BloodRequest", b =>
                {
                    b.HasOne("HuyetMach175.Api.Data.Entities.User", "Doctor")
                        .WithMany("DoctorRequests")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.BloodRequestItem", b =>
                {
                    b.HasOne("HuyetMach175.Api.Data.Entities.BloodComponentType", "ComponentType")
                        .WithMany("RequestItems")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HuyetMach175.Api.Data.Entities.BloodRequest", "Request")
                        .WithMany("Items")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentType");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.BloodReturn", b =>
                {
                    b.HasOne("HuyetMach175.Api.Data.Entities.BloodAllocation", "Allocation")
                        .WithOne("BloodReturn")
                        .HasForeignKey("HuyetMach175.Api.Data.Entities.BloodReturn", "AllocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HuyetMach175.Api.Data.Entities.User", "ReceivedByUser")
                        .WithMany("ReceivedReturns")
                        .HasForeignKey("ReceivedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HuyetMach175.Api.Data.Entities.User", "ReturnedByUser")
                        .WithMany("ReturnedReturns")
                        .HasForeignKey("ReturnedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Allocation");

                    b.Navigation("ReceivedByUser");

                    b.Navigation("ReturnedByUser");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.BloodTestResult", b =>
                {
                    b.HasOne("HuyetMach175.Api.Data.Entities.BloodBag", "Bag")
                        .WithMany("TestResults")
                        .HasForeignKey("BagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HuyetMach175.Api.Data.Entities.User", "Technician")
                        .WithMany("TestResults")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bag");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.DonationAppointment", b =>
                {
                    b.HasOne("HuyetMach175.Api.Data.Entities.DonationCampaign", "Campaign")
                        .WithMany("Appointments")
                        .HasForeignKey("CampaignId");

                    b.HasOne("HuyetMach175.Api.Data.Entities.Donor", "Donor")
                        .WithMany("Appointments")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.DonationCampaign", b =>
                {
                    b.HasOne("HuyetMach175.Api.Data.Entities.User", "ApprovedByUser")
                        .WithMany("ApprovedCampaigns")
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HuyetMach175.Api.Data.Entities.User", "CreatedByUser")
                        .WithMany("CreatedCampaigns")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.DonationSession", b =>
                {
                    b.HasOne("HuyetMach175.Api.Data.Entities.DonationAppointment", "Appointment")
                        .WithOne("DonationSession")
                        .HasForeignKey("HuyetMach175.Api.Data.Entities.DonationSession", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HuyetMach175.Api.Data.Entities.User", "Doctor")
                        .WithMany("DoctorSessions")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HuyetMach175.Api.Data.Entities.User", "Phlebotomist")
                        .WithMany("PhlebotomistSessions")
                        .HasForeignKey("PhlebotomistId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("Phlebotomist");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.Notification", b =>
                {
                    b.HasOne("HuyetMach175.Api.Data.Entities.User", "RecipientUser")
                        .WithMany("ReceivedNotifications")
                        .HasForeignKey("RecipientUserId");

                    b.HasOne("HuyetMach175.Api.Data.Entities.Department", "TargetDepartment")
                        .WithMany("Notifications")
                        .HasForeignKey("TargetDepartmentId");

                    b.HasOne("HuyetMach175.Api.Data.Entities.Role", "TargetRole")
                        .WithMany("Notifications")
                        .HasForeignKey("TargetRoleId");

                    b.Navigation("RecipientUser");

                    b.Navigation("TargetDepartment");

                    b.Navigation("TargetRole");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.PreScreeningSurvey", b =>
                {
                    b.HasOne("HuyetMach175.Api.Data.Entities.DonationAppointment", "Appointment")
                        .WithOne("PreScreeningSurvey")
                        .HasForeignKey("HuyetMach175.Api.Data.Entities.PreScreeningSurvey", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("HuyetMach175.Api.Data.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.RolePermission", b =>
                {
                    b.HasOne("HuyetMach175.Api.Data.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HuyetMach175.Api.Data.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.User", b =>
                {
                    b.HasOne("HuyetMach175.Api.Data.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.UserRole", b =>
                {
                    b.HasOne("HuyetMach175.Api.Data.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HuyetMach175.Api.Data.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.BloodAllocation", b =>
                {
                    b.Navigation("BloodReturn");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.BloodBag", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("DerivedBags");

                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.BloodComponentType", b =>
                {
                    b.Navigation("BloodBags");

                    b.Navigation("RequestItems");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.BloodRequest", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.Department", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.DonationAppointment", b =>
                {
                    b.Navigation("DonationSession");

                    b.Navigation("PreScreeningSurvey");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.DonationCampaign", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.DonationSession", b =>
                {
                    b.Navigation("BloodBags");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.Donor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.Role", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.StorageLocation", b =>
                {
                    b.Navigation("BloodBags");
                });

            modelBuilder.Entity("HuyetMach175.Api.Data.Entities.User", b =>
                {
                    b.Navigation("ApprovedCampaigns");

                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedCampaigns");

                    b.Navigation("DoctorRequests");

                    b.Navigation("DoctorSessions");

                    b.Navigation("IssuedAllocations");

                    b.Navigation("PhlebotomistSessions");

                    b.Navigation("ReceivedAllocations");

                    b.Navigation("ReceivedNotifications");

                    b.Navigation("ReceivedReturns");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ReservedAllocations");

                    b.Navigation("ReturnedReturns");

                    b.Navigation("TestResults");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
